user_usuario:
    resource: "@UserBundle/Resources/config/routing/usuario.yml"
    prefix:   /usuario

login_route:
    path:     /login
    defaults: { _controller: UserBundle:Security:login }

login_check:
    path: /login_check
    # no controller is bound to this route
    # as it's handled by the Security system